Importing the Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Importing the Dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Classification3_exams.csv")
df

gender race/ethnicity parental level of education         lunch  \
0    female        group D                some college      standard   
1      male        group D          associate's degree      standard   
2    female        group D                some college  free/reduced   
3      male        group B                some college  free/reduced   
4    female        group D          associate's degree      standard   
..      ...            ...                         ...           ...   
995    male        group C                some college      standard   
996    male        group C                some college      standard   
997  female        group A                 high school      standard   
998    male        group E                 high school      standard   
999    male        group D                 high school      standard   

    test preparation course  math score  reading score  writing score  
0                 completed          59             70             78  
1                      none          96             93             87  
2                      none          57             76             77  
3                      none          70             70             63  
4                      none          83             85             86  
..                      ...         ...            ...            ...  
995                    none          77             77             71  
996                    none          80             66             66  
997               completed          67             86             86  
998                    none          80             72             62  
999                    none          58             47             45  

[1000 rows x 8 columns]

In [ ]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
df.describe()

math score  reading score  writing score
count  1000.000000    1000.000000    1000.000000
mean     67.810000      70.382000      69.140000
std      15.250196      14.107413      15.025917
min      15.000000      25.000000      15.000000
25%      58.000000      61.000000      59.000000
50%      68.000000      70.500000      70.000000
75%      79.250000      80.000000      80.000000
max     100.000000     100.000000     100.000000

Dividing dependent and independent variables

In [ ]:
X = df.drop('race/ethnicity',axis = 1).values
y = df.iloc[:,1].values

In [ ]:
X.shape

(1000, 7)

In [ ]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [ ]:
X.shape

(1000, 7)

In [ ]:
y.shape

(1000,)

Label Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in range(0,4):
    X[:,i] = le.fit_transform(X[:,i])
y = le.fit_transform(y)

In [ ]:
X

array([[0, 4, 1, ..., 59, 70, 78],
       [1, 0, 1, ..., 96, 93, 87],
       [0, 4, 0, ..., 57, 76, 77],
       ...,
       [0, 2, 1, ..., 67, 86, 86],
       [1, 2, 1, ..., 80, 72, 62],
       [1, 2, 1, ..., 58, 47, 45]], dtype=object)

In [ ]:
y

array([3, 3, 3, 1, 3, 2, 4, 1, 2, 2, 1, 1, 1, 0, 2, 4, 2, 2, 4, 3, 2, 3,
       1, 4, 3, 1, 3, 3, 4, 3, 1, 3, 1, 3, 3, 0, 4, 3, 2, 4, 2, 2, 1, 3,
       1, 2, 0, 2, 4, 3, 4, 4, 3, 1, 2, 2, 3, 4, 2, 2, 3, 2, 3, 2, 1, 1,
       2, 1, 2, 3, 2, 3, 2, 3, 4, 1, 1, 2, 0, 1, 2, 3, 0, 2, 3, 3, 3, 4,
       1, 2, 2, 2, 2, 3, 2, 2, 3, 1, 1, 2, 3, 2, 3, 2, 2, 3, 1, 1, 2, 4,
       3, 1, 2, 2, 1, 4, 4, 2, 1, 1, 3, 3, 3, 1, 3, 4, 1, 3, 2, 2, 2, 2,
       3, 3, 2, 2, 4, 4, 3, 2, 2, 3, 2, 4, 3, 0, 3, 4, 2, 2, 3, 1, 2, 0,
       4, 1, 1, 2, 1, 3, 4, 2, 3, 1, 0, 4, 2, 4, 3, 3, 1, 3, 0, 4, 3, 3,
       1, 4, 2, 2, 1, 1, 0, 0, 1, 3, 2, 2, 3, 2, 2, 0, 1, 3, 3, 3, 2, 1,
       2, 4, 0, 3, 1, 4, 1, 1, 2, 4, 2, 2, 4, 4, 4, 1, 0, 3, 3, 0, 3, 4,
       2, 4, 2, 4, 3, 1, 3, 4, 2, 2, 1, 4, 1, 2, 3, 2, 1, 1, 3, 1, 1, 3,
       3, 1, 2, 2, 2, 2, 0, 2, 2, 2, 1, 1, 3, 1, 1, 2, 1, 2, 2, 3, 1, 0,
       2, 2, 3, 3, 3, 2, 2, 3, 4, 2, 3, 1, 3, 2, 0, 0, 2, 2, 2, 1, 1, 4,
       0, 1, 2, 0, 2, 3, 4, 2, 3, 2, 1, 3, 1, 2, 2,

Splitting test and train set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,4:] = sc.fit_transform(X_train[:,4:])
X_test[:,4:] = sc.transform(X_test[:,4:])

In [ ]:
X_train

array([[1, 0, 0, ..., 0.9373191867493751, 1.1338696508259662,
        0.6041553409007787],
       [0, 4, 1, ..., 1.0032811281110483, 1.4930870279290762,
        1.5501276347758974],
       [1, 0, 1, ..., 0.7394333626643556, 0.4872783720403685,
        0.4014469922132533],
       ...,
       [1, 1, 0, ..., -0.3159576991224148, -0.8059041855308271,
        -1.2202197972869502],
       [1, 0, 1, ..., 0.5415475385793361, 0.6309653228816124,
        0.7392942400257957],
       [1, 0, 1, ..., 1.794824424451126, 1.1338696508259662,
        0.9420025887133211]], dtype=object)

Training with SVM

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf')
classifier.fit(X_train, y_train)

SVC()

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
y_test

array([3, 4, 1, 2, 3, 4, 4, 3, 3, 3, 4, 2, 2, 3, 1, 0, 3, 3, 2, 1, 1, 1,
       3, 3, 3, 0, 4, 2, 1, 3, 2, 1, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2,
       2, 2, 2, 2, 1, 3, 1, 2, 3, 3, 3, 1, 3, 3, 1, 4, 2, 4, 0, 2, 1, 3,
       0, 3, 0, 4, 3, 1, 4, 2, 2, 2, 3, 2, 0, 4, 4, 4, 2, 3, 3, 2, 3, 3,
       2, 2, 4, 4, 4, 2, 1, 4, 3, 0, 3, 1, 4, 3, 1, 4, 3, 3, 2, 3, 2, 3,
       1, 1, 1, 4, 3, 3, 3, 2, 2, 1, 3, 2, 2, 2, 3, 2, 3, 3, 1, 2, 3, 1,
       2, 2, 1, 3, 3, 3, 1, 4, 3, 2, 4, 1, 4, 3, 1, 4, 4, 3, 3, 2, 1, 4,
       2, 2, 3, 3, 2, 4, 3, 0, 2, 2, 4, 2, 2, 3, 1, 0, 2, 3, 4, 3, 2, 1,
       2, 2, 0, 2, 3, 2, 2, 2, 1, 4, 1, 4, 2, 1, 2, 3, 4, 1, 3, 4, 1, 2,
       4, 2])

In [ ]:
y_pred

array([2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2,
       2, 3, 2, 3, 2, 3, 2, 3, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3,
       4, 2, 2, 2, 3, 3, 2, 2, 4, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 3, 2, 2, 2, 2, 4, 3, 3, 2, 3, 2, 3, 2, 1, 2, 3, 2, 2, 2,
       2, 2, 2, 3, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 4, 2,
       2, 2, 2, 3, 3, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 3, 2, 2, 3,
       2, 2, 2, 2, 3, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 4,
       2, 2, 2, 2, 3, 2, 2, 2, 2, 4, 4, 4, 3, 3, 2, 2, 2, 2, 4, 2, 3, 4,
       2, 3, 2, 3, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 2, 2, 2,
       4, 3])

Evaluating Model Performance

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,f1_score
print(confusion_matrix(y_test,y_pred))
print(f'Accuracy Score : {accuracy_score(y_test,y_pred)}')

[[ 0  0  8  2  0]
 [ 0  0 29  4  1]
 [ 0  2 47 10  5]
 [ 0  1 45 11  2]
 [ 0  0 19  7  7]]
Accuracy Score : 0.325
